# Generated by Django 3.0.8 on 2020-07-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('file_link', models.CharField(max_length=200)),
                ('file_itself', models.FileField(upload_to='')),
                ('living_time', models.DecimalField(max_digits=50, decimal_places=20)),
            ],
        ),
    ]
