# Generated by Django 3.0.8 on 2020-07-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharingsite', '0001_initial'),
    ]

    operations = [

        migrations.AlterField(
            model_name='file',
            name='living_time',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
    ]
