# Generated by Django 3.0.8 on 2020-07-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharingsite', '0003_auto_20200722_1133'),
    ]

    operations = [

    ]
