# Generated by Django 3.0.8 on 2020-07-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharingsite', '0004_file_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='living_time',
            field=models.CharField(max_length=100),
        ),
    ]
