# Generated by Django 3.0.8 on 2020-07-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharingsite', '0005_auto_20200722_1134'),
    ]

    operations = [
    ]
