# Generated by Django 3.0.8 on 2020-07-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharingsite', '0006_auto_20200722_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='living_time',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
