# Generated by Django 3.0.8 on 2020-07-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharingsite', '0007_auto_20200722_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='living_time',
            field=models.DecimalField(decimal_places=0, max_digits=50),
        ),
    ]
