# Generated by Django 3.0.8 on 2020-07-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharingsite', '0008_auto_20200727_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='living_time',
            field=models.TimeField(),
        ),
    ]
