# Generated by Django 3.0.8 on 2020-07-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharingsite', '0010_auto_20200730_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='living_time',
            field=models.TimeField(),
        ),
    ]
