# Generated by Django 3.0.8 on 2020-07-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharingsite', '0012_auto_20200730_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='living_time',
            new_name='living_time_minutes',
        ),
    ]
