# Generated by Django 3.0.8 on 2020-07-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharingsite', '0013_auto_20200730_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='living_time_minutes',
            new_name='living_time_in_hours',
        ),
    ]
