# Generated by Django 3.0.8 on 2020-07-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharingsite', '0014_auto_20200730_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='living_time_in_hours',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
