# Generated by Django 3.0.8 on 2020-07-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharingsite', '0015_auto_20200730_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='living_time_in_hours',
            new_name='hours_to_delete',
        ),
        migrations.AddField(
            model_name='file',
            name='minutes_to_delete',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='seconds_to_delete',
            field=models.DecimalField(decimal_places=0, default=2, max_digits=2),
            preserve_default=False,
        ),
    ]
