# Generated by Django 3.0.8 on 2020-07-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharingsite', '0016_auto_20200731_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='hours_to_delete',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='file',
            name='minutes_to_delete',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='file',
            name='seconds_to_delete',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
        ),
    ]
