# Generated by Django 3.0.8 on 2020-07-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharingsite', '0017_auto_20200731_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='cur_day',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='cur_month',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='cur_year',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='minutes_to_delete',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='file',
            name='seconds_to_delete',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
