# Generated by Django 3.0.8 on 2020-07-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharingsite', '0018_auto_20200731_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='seconds_to_delete',
        ),
        migrations.AlterField(
            model_name='file',
            name='cur_day',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='file',
            name='cur_month',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='file',
            name='cur_year',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
